### PR TITLE
Add, remove or replace a record should update inverse relationships

### PR DESCRIPTION
**Pull request by julfla**
As for `replaceRelatedRecord` inverse relationships should be updated for transforms
* `addRecord`: when creating a record with relationships
* `removeRecord`: always
* `replaceRecord`: when changing the relationships

### CODE REVIEW

**Comment by julfla** [comment]
Hi, I ran into this issue today. 

Also, I'm not very sure about the proposed fix.

What do you think ?

**Comment by hongaar** [comment]
Thanks again for your PR!

Two questions come to mind:
- Why is the implementations for `addRecord`/`replaceRecord` different from `removeRecord`? The first case seem to be a bit more efficient.
- Any idea why the tests are failing just for Node v6?

**Comment by julfla** [comment]
Hi, 

Pleasure is mine, this project is very useful to me.

I updated the comments to try clarify the difference between add/replace and remove.

- In the case of add/replace, according to orbitjs [doc], record is of type `Record`, as such it may contain
    relationships. Only those can be impacted.
- For remove however, record if of type `RecordIdentity`. As it does not provide any info expect the 
    record type and id, we have to assume that all the relationships defined in the schema can be 
    impacted.

I could also fix the node 6 tests. I not very fluent in js, and didn't know that `Object.values` is quite new and node 6 does not support it.

**Comment by julfla** [comment]
@hongaar I have been using this patch for a couple of days now.

It seems ok.

Please let me know if I can be of any help on the subject.

**Comment by hongaar** [comment]
Looking good 🎉

Thanks again @julfla

**Pull request merged**
