### PR TITLE
Some ideas for this repo: Typescript, helpers, new context api, etc

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
I was working out some ideas of how things could be modernized / improved for greater code correctness.
This stemmed from an effort to just copy-paste some helpers from https://github.com/sillsdev/appbuilder-portal into react-orbitjs, but got hung up on the ts <-> js conversion between projects -- so, I decided to investigate would it would look like if react-orbitjs were in typecsript.

My goal for this PR is not to have it merged, but to discuss a strategy for incrementally adopting things:
 - Typescript
 - Helpers
 - Eventually, new context API (the one in use is deprecated)

What I was kind of thinking was:
 1. convert from using the babel transpiler to tsc / or configure babel to work with ts
 2. simplify distributables (unless TS can output multiple? idk)
 3. start adding helpers as pure functions, such as:
   - query (HoC)
   - withRelationships
   - create, update, etc (for reduced json-api usage in actual react project code)
   - etc

I'd love to get your thoughts, thanks!

files of interest (so you don't need to scroll through this PR,
 - DataProvider: https://github.com/exivity/react-orbitjs/pull/22/files#diff-83c08e8ea764fe88646b457c29466c80R1
    - lightweight, just sets up an `OrbitProvider` from the `OrbitContext`

 - DataSubscriber: https://github.com/exivity/react-orbitjs/pull/22/files#diff-fe1d20b28afa818ddc30eab6b5b15471R1
   - this is where most of the existing code in `withData` would go
 - withData: https://github.com/exivity/react-orbitjs/pull/22/files#diff-f4ff88daea3bb111de119345db14251eR11
   - uses the `OrbitConsumer` from the `OrbitContext` and wrapers in the Subscriber HoC to set up the subscribed updates and such

 - withRelationship: https://github.com/exivity/react-orbitjs/pull/22/files#diff-737d53dc8c3fd876b957c590511d7fddR26
   - example of a helper that I'd eventually want to bring in to this project :)

### CODE REVIEW

**Comment by hongaar** [comment]
Wow, thanks for all your work. I will take a deep dive into your proposed changes over the next week or so. We are currently working on a lightweight ORM layer on top of react-orbitjs (https://github.com/exivity/proton), a bit like the proposal in https://github.com/orbitjs/orbit/issues/529. 

It will be interesting to discover how all those things relate.

**Comment by NullVoxPopuli** [comment]
oh that'd be super cool!

fwiw, these changes are incomplete, and non-functional, as I didn't get to implementing all the subscription stuff yet

**Comment by NullVoxPopuli** [comment]
something I've noticed as I've been using with react-orbitjs, subscription updates seem somewhat slow with the current implementation. I haven't had the time to try to find the source of the lack of react time, but I'm wondering if it could be:
 - orbit.js itself
 - react-orbitjs' subscriptions

in order to replicate the slowness:
 - clone https://github.com/sillsdev/appbuilder-portal/
 - cd into root of project
 - Terminal 1: `./run up:local:start`
 - Terminal 2: `./run dc start api`
 - Terminal 3: `cd source/SIL.AppBuilder.Portal.Frontend && yarn && yarn start:dev`
 - Termianl 4: `vim /etc/hosts`, append:

```
127.0.0.1 api
127.0.0.1 db.docker
127.0.0.1 db
```
 - Terminal 5: `./run bootstrap`
 - visit: http://localhost:9091/projects/organization
 - click a kebab on the right hand side, click archive. 
    - notice the ~ 1s wait time until it's archived / the row is faded
    - there is the specific change to subscribe to a single project on the row of projects: https://github.com/sillsdev/appbuilder-portal/pull/318/files#diff-26df24819f42add37f296c6bbb02890aR103

**Comment by Michiel87** [comment]
Are you on the latest release of react-orbitjs? We ran across something similar and merged an improvement.

**Comment by NullVoxPopuli** [comment]
@Michiel87 looks like the branch I was using is a few commits behind: https://github.com/NullVoxPopuli/react-orbitjs/pull/1

**Comment by hongaar** [comment]
Closing in favour of #25.

**Pull request closed without merging**
