### PR TITLE
feat: add support for orbitjs v0.17.x

### PR DESCRIPTION
**Pull request by bradjones1**
Resolves https://github.com/exivity/react-orbitjs/issues/83

### CODE REVIEW

**Comment by hongaar** [comment]
Thanks for your PR! Would this also work with the v0.16.x branch?

**Comment by hongaar** [comment]
@bradjones1 I created a test for the `0.17.x` branch which is currently failing (see https://github.com/exivity/react-orbitjs/runs/3230537511). I'll see what I can do to add support for the upcoming version.

**Comment by hongaar** [comment]
Still some errors for 0.17.x branch. Running out of time now, will try to pick this up later. Help is welcome!
```
Tests:       10 failed, 20 passed, 30 total
```

**Comment by bradjones1** [comment]
Awesome! Thank you.

**Pull request merged**
